---
- name: create data dir
  file:
    path: "{{minio_dir}}"
    state: directory

- name: copy docker files
  template:
    src: "{{item}}"
    dest: "{{minio_dir}}/{{item}}"
  loop:
    - "docker-compose.yml"

- name: docker compose down
  shell:
    cmd: "docker compose down"
    chdir: "{{minio_dir}}"
  failed_when: false

- name: docker compose up -d
  shell:
    cmd: "docker compose up -d"
    chdir: "{{minio_dir}}"