---
- name: set_fact
  set_fact:
    install_tmp_dir: /data/tmp/keepalived_install

- name: create data dir
  file:
    path: "{{item}}"
    mode: "0755"
    state: directory
  loop:
    - "{{keepalived_path}}"
    - "{{install_tmp_dir}}"

- name: unarchive devel-rpm-packages
  unarchive:
    src: 'files/devel-rpm-packages-{{ansible_architecture}}.tar'
    dest: '{{install_tmp_dir}}'

- name: rpm install devel-rpm-packages
  shell:
    cmd: "rpm -Uvh *.rpm --nodeps"
    chdir: "{{install_tmp_dir}}"
  failed_when: false

- name: unarchive keepalived-{{keepalived_version}} source
  unarchive:
    src: 'files/keepalived-{{keepalived_version}}.tar.gz'
    dest: '{{install_tmp_dir}}'

- name: install keepalived
  shell:
    cmd: "{{item}}"
    chdir: "{{install_tmp_dir}}/keepalived-{{keepalived_version}}"
  loop:
    - './configure --prefix=/usr/local/keepalived && make -j 4 && make install'
    - 'ln -sf /usr/local/keepalived/sbin/keepalived /usr/sbin/keepalived'

- name: copy keepalived to /etc/init.d
  copy:
    src: '{{install_tmp_dir}}/keepalived-{{keepalived_version}}/keepalived/etc/init.d/keepalived'
    dest: /etc/init.d/keepalived
    remote_src: yes

- name: append keepalived to auto startup
  shell:
    cmd: "{{item}}"
  loop:
    - "chmod a+wrx /etc/init.d/keepalived"
    - "chkconfig --level 345 keepalived on"
    - "chkconfig --list"

- name: stop selinux
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=disabled
  failed_when: false

- name: rm {{install_tmp_dir}}
  shell:
    cmd: "rm -fr {{install_tmp_dir}}"
  when: "'/data/tmp/' in install_tmp_dir"