---
image_files:
  - { type: "apps",repository: "somersault-cloud/system",tag: "1.0.0-snapshot" }
  - { type: "apps",repository: "somersault-cloud/infra",tag: "1.0.0-snapshot" }
  - { type: "apps",repository: "somersault-cloud/bpm",tag: "1.0.0-snapshot" }
  - { type: "apps",repository: "somersault-cloud/report",tag: "1.0.0-snapshot" }
  - { type: "apps",repository: "somersault-cloud/gateway",tag: "1.0.0-snapshot" }
  - { type: "apps",repository: "somersault-cloud/monitor",tag: "1.0.0-snapshot" }
  - { type: "apps",repository: "somersault-cloud/iot",tag: "1.0.0-snapshot" }
  - { type: "apps",repository: "somersault-cloud/openresty",tag: "1.0.0-snapshot" }
  - { type: "basic",repository: "redis",tag: "6.2.0" }
  - { type: "basic",repository: "apache/rocketmq",tag: "4.9.4" }
  - { type: "basic",repository: "apacherocketmq/rocketmq-dashboard",tag: "1.0.0" }
  - { type: "basic",repository: "nacos/nacos-server",tag: "v2.2.1-slim" }
  - { type: "basic",repository: "xuxueli/xxl-job-admin",tag: "2.2.0" }
  - { type: "basic",repository: "prom/prometheus",tag: "v2.37.3" }
  - { type: "basic",repository: "prom/alertmanager",tag: "v0.24.0" }
  - { type: "basic",repository: "timonwong/prometheus-webhook-dingtalk",tag: "v2.1.0" }
  - { type: "basic",repository: "grafana/grafana",tag: "8.5.24" }
  - { type: "basic",repository: "grafana/loki",tag: "2.7.5" }
  - { type: "basic",repository: "grafana/promtail",tag: "2.7.5" }
  - { type: "basic",repository: "prom/mysqld-exporter",tag: "v0.14.0" }
  - { type: "basic",repository: "oliver006/redis_exporter",tag: "v1.45.0" }
  - { type: "basic",repository: "apache/skywalking-oap-server",tag: "8.9.0" }
  - { type: "basic",repository: "apache/skywalking-ui",tag: "8.9.0" }
  - { type: "basic",repository: "prom/mysqld-exporter",tag: "v0.14.0" }