---
- name: set_fact
  set_fact:
    db_user_hosts:
      - "127.0.0.1"
      - "{{mysql_user_host}}"
      - "{{hostvars[groups['docker'][0]]['docker_address_pools'].split('0.0')[0]}}%"

- name: print db_user_hosts
  debug:
    msg: "{{db_user_hosts}}"

- name: "generate files/init-db.sql to local used for DBA"
  template:
    src: "init-db.sql"
    dest: "{{role_path}}/files/init-db.sql"
  delegate_to: localhost
  become: false

- name: Get mysql master addr from hosts for target
  set_fact:
    mysql_master_vip: "{{hostvars[item]['mysql_master_vip']}}"
  when: hostvars[item]['mysql_master_vip'] is defined and hostvars[item]['mysql_master_vip'] != 'auto'
  with_items: "{{groups['mysql']}}"

- name: Get mysql master addr from hosts for auto
  set_fact:
    mysql_master_vip: "{{hostvars[item]['ansible_ssh_host']}}"
  when: hostvars[item]['mysql_master_vip'] is defined and hostvars[item]['mysql_master_vip'] == 'auto'
  with_items: "{{groups['mysql']}}"

- name: "select count(*) from mysql.user where user = '{{mysql_user}}';"
  shell: >
    mysql -NBe "select count(*) from mysql.user where user = '{{mysql_user}}';"
    -uroot -p"{{mysql_root_password}}" -h"{{mysql_master_vip}}"
  register: initdata_count
  failed_when: false
  when:
    - mysql_root_password | default('') != ''
    - hostvars[inventory_hostname]['mysql_master_vip'] is defined

- name: result of select count(*) from mysql.user where user = '{{mysql_user}}'
  debug:
    msg: "{{initdata_count.stdout}}"
  when:
    - mysql_root_password | default('') != ''
    - hostvars[inventory_hostname]['mysql_master_vip'] is defined

- include_tasks: initdb.yml
  when:
    - mysql_root_password | default('') != ''
    - hostvars[inventory_hostname]['mysql_master_vip'] is defined
    - initdata_count.stdout  == '0' or initdata_count.stdout  == ''
