---
- name: set_fact docker_image_repo
  set_fact:
    docker_image_repo: "{{docker_repo_addr}}/"
  when: docker_repo_addr | default('') != ''

- name: create data dir
  file:
    path: "{{item}}"
    mode: "0755"
    state: directory
  loop:
    - "{{redis_dir}}/data"
    - "{{redis_dir}}"

# 提取hosts中主节点IP地址为从节点指向主节点的参数
- name: Get master host ip from hosts config
  set_fact:
    redis_requirepass: "{{hostvars[item]['redis_requirepass']}}"
    redis_master_host: "{{hostvars[item]['ansible_ssh_host']}}"
    redis_master_port: "{{hostvars[item]['redis_port']}}"
  when: hostvars[item]['sentinel_master_name'] is defined
  with_items: "{{groups['redis']}}"

- name: copy docker files
  template:
    src: "{{ item }}"
    dest: "{{redis_dir}}/{{ item }}"
  loop:
    - docker-compose.yml

- name: copy redis conf file
  template:
    src: "{{ item }}"
    dest: "{{redis_dir}}/{{ item }}"
  loop:
    - redis.conf

- name: docker compose down
  shell:
    cmd: "docker compose down"
    chdir: "{{redis_dir}}"
  failed_when: false

- name: docker compose up -d
  shell:
    cmd: "docker compose up -d"
    chdir: "{{redis_dir}}"