# 前台运行： docker compose up
# 后台运行： docker compose up -d
# 拉取新镜像运行： docker compose up -d --pull always
# 删除容器： docker compose down
# 清除异常容器： docker rm $(sudo docker ps -qf status=exited)
# 清空失效镜像： docker rmi `docker images | grep '<none>' | awk '{print $3}'`
version: "3"
services:
  openresty:
    container_name: openresty
    image: "{{docker_image_repo | default('')}}somersault-cloud/openresty:{{web_server_version}}"
    restart: always
    ports:
      - "{{http_port}}:{{http_port}}"
      - "{{dashboard_admin_port}}:{{dashboard_admin_port}}"
{% if api_url_prefix_target is defined  %}
    environment:
      API_URL_PREFIX_SOURCE: "{{api_url_prefix_source}}"
      API_URL_PREFIX_TARGET: "{{api_url_prefix_target}}"
{% endif %}
    volumes:
      - ./conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./conf/cert:/usr/local/openresty/nginx/conf/cert
      - ./html/www:/usr/local/openresty/nginx/html/www
      - ./logs:/usr/local/openresty/nginx/logs