# 前台运行： docker compose up
# 后台运行： docker compose up -d
# 重建容器运行： docker compose up -d --build
# 显示构建信息运行： DOCKER_BUILDKIT=0  docker compose up -d --build
# 删除容器： docker compose down
version: "3.8"
services:
  minio:
    image: quay.io/minio/minio:{{minio_version}}
    container_name: "minio"
    ports:
      - 9000:9000 # 服务端口
      - {{minio_console_port}}:{{minio_console_port}} # 控制台端口
    environment:
      - "MINIO_ACCESS_KEY={{minio_console_user}}" # 登陆账号
      - "MINIO_SECRET_KEY={{minio_console_passwd}}" # 密码
    volumes: # 挂载数据卷
      - "./data:/data"
      - "./config:/root/.minio"
    command: server /data --console-address ":{{minio_console_port}}" # 容器启动时执行的指令
    restart: always # 容器退出时总是重启容器