---
- name: Check keepalived exists
  stat:
    path: /usr/sbin/keepalived
  register: keepalived_result

- name: Get keepalived_master_ip from hosts config
  set_fact:
    keepalived_master_ip: "{{ansible_ssh_host}}"
    openresty_keepalived_vip: "{{ansible_ssh_host}}"

- include_tasks: keepalived.yml
  when:
    - keepalived_result.stat.exists == False
    - groups['apps_openresty'] | length >= 2

- include_tasks: keepalived_config.yml
  when:
    - groups['apps_openresty'] | length >= 2

- name: print access info
  debug:
    msg: "Access Endpoint: http://{{openresty_keepalived_vip}}:{{http_port}}"
  when: inventory_hostname == groups['apps_openresty'][0]