---
- name: Check docker exists
  stat:
    path: /etc/docker/daemon.json
  register: docker_result

- include_tasks: docker_install.yml
  when: docker_result.stat.exists == False

- name: setup docker daemon.json
  template:
    src: "daemon.json"
    dest: "/etc/docker/daemon.json"

- name: Ensure docker is started and enabled on boot.
  service:
    name: "docker"
    state: restarted
    enabled: "true"