# {% set redis_sentinel_hosts = [] %}
# {% for item in groups['sentinel'] %}
#   {{  redis_sentinel_hosts.append("{}:{}".format(hostvars[item]['ansible_ssh_host'], hostvars[item]['sentinel_port'])) }}
# {% endfor %}
# {% set redis_sentinel_hosts_join = redis_sentinel_hosts |  join(',') %}

--- #################### 数据库相关配置 ####################
spring:
  datasource:
    dynamic: # 多数据源配置
      primary: master
      datasource:
        master:
          name: somersault_cloud_iot
          url: jdbc:mysql://{{mysql_replication_master_addr}}/${spring.datasource.dynamic.datasource.master.name}?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8&nullCatalogMeansCurrent=true
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: somersault_cloud
          password: {{mysql_passwd}}
        slave:
          name: somersault_cloud_iot
          url: jdbc:mysql://{{mysql_replication_slave_addr}}/${spring.datasource.dynamic.datasource.slave.name}?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8&nullCatalogMeansCurrent=true
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: somersault_cloud
          password: {{mysql_passwd}}

  # Redis 配置
  redis:
    database: 0        # Redis数据库索引（默认为0）
    password: {{redis_requirepass}}   # Redis服务器连接密码（默认为空）
    timeout: 3000      # 连接超时时间（毫秒）
{% if groups['sentinel'] | length >= 1 %}
    sentinel:
      nodes: {{redis_sentinel_hosts_join}} # 集群哨兵节点配置，多个节点之间用英文逗号分割
      master: {{sentinel_master_name}}     # Redis主节点名称，哨兵配置文件中的名称
{% else %}
    host: {{redis_replication_master_host}}    # Redis服务器地址
    port: {{redis_replication_master_port}}    # Redis服务器连接端口
{% endif %}

--- #################### 框架相关配置 ####################
biz:
  demo: false # 演示模式