---
- name: create data dir
  file:
    path: "{{item}}"
    mode: "0755"
    state: directory
  loop:
    - "{{apps_openresty_dir}}/logs"
    - "{{apps_openresty_dir}}/conf"
    - "{{apps_openresty_dir}}/conf/conf.d"
    - "{{apps_openresty_dir}}/conf/cert"
    - "{{apps_openresty_dir}}/html"
    - "{{apps_openresty_dir}}/html/www"

- name: set_fact docker_image_repo
  set_fact:
    docker_image_repo: "{{docker_repo_addr}}/"
  when: docker_repo_addr | default('') != ''

- name: Get keepalived_vip from hosts config
  set_fact:
    openresty_keepalived_vip: "{{hostvars[item]['openresty_keepalived_vip']}}"
  when: hostvars[item]['openresty_keepalived_vip'] is defined
  with_items: "{{groups['apps_openresty']}}"

- name: Get api_url_prefix from hosts config
  set_fact:
    api_url_prefix_target: "{{api_url_prefix}}"
  when: api_url_prefix is defined

- name: copy html files
  copy:
    src: "{{ item }}"
    dest: "{{apps_openresty_dir}}/{{ item }}"
  loop:
    - html/www/index.html

- name: copy conf files
  template:
    src: "{{ item }}"
    dest: "{{apps_openresty_dir}}/conf/{{ item }}"
  loop:
    - nginx.conf

- name: copy conf.d files
  template:
    src: "{{ item }}"
    dest: "{{apps_openresty_dir}}/conf/conf.d/{{ item | basename }}"
  with_fileglob:
    - "templates/conf.d/*"

- name: copy docker files
  template:
    src: "{{ item }}"
    dest: "{{apps_openresty_dir}}/{{ item }}"
  loop:
    - docker-compose.yml

- name: "docker login {{docker_repo_addr}}"
  shell: "docker login -u {{docker_repo_user}} -p {{docker_repo_passwd}} {{docker_repo_addr}}"
  when: docker_repo_passwd is defined
  register: docker_login_result

- name: "show docker login result"
  debug:
    msg: "{{docker_login_result.stdout}}"
  when: docker_repo_passwd is defined

- name: docker compose down
  shell:
    cmd: "docker compose down"
    chdir: "{{apps_openresty_dir}}"
  failed_when: false

- name: docker compose up -d --pull always
  shell:
    cmd: "docker compose up -d --pull always"
    chdir: "{{apps_openresty_dir}}"