# 前台运行： docker compose up
# 后台运行： docker compose up -d
# 重建容器运行： docker compose up -d --build
# 显示构建信息运行： DOCKER_BUILDKIT=0  docker compose up -d --build
# 删除容器： docker compose down
# 清除异常容器： docker rm $(sudo docker ps -qf status=exited)
# 清空失效镜像： docker rmi `docker images | grep '<none>' | awk '{print $3}'`

version: "3.8"
services:
  jenkins:
    build:
      context: ./docker
    container_name: jenkins
    image: jenkins/jenkins-x:{{jenkins_version}}
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/docker/daemon.json:/etc/docker/daemon.json:ro
      - ./data/jenkins:/var/jenkins_home
      - ./data/m2:/root/.m2
    environment:
      JAVA_OPTS: "-Xms512m -Xmx2048m"
      JENKINS_OPTS: "--prefix=/jenkins"
      # https://github.com/jenkinsci/docker/blob/master/README.md#setting-update-centers
      JENKINS_UC: "https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/update-center.json"
      TZ: 'Asia/Shanghai'
    network_mode: host
    #ports:
    #  - {{jenkins_port}}:8080
    privileged: true
    restart: always