---
- name: create data dir
  file:
    path: "{{registry_dir}}"
    state: directory

- name: install tool software
  yum:
    name: [ 'httpd-tools' ]
    state: installed
  retries: 3

- name: create htpasswd file
  shell:
    cmd: "htpasswd -Bbn {{repo_docker_user}} {{repo_docker_passwd}} > {{registry_dir}}/htpasswd"
    chdir: "{{registry_dir}}"

- name: copy docker files
  template:
    src: "{{item}}"
    dest: "{{registry_dir}}/{{item}}"
  loop:
    - "docker-compose.yml"

- name: docker compose down
  shell:
    cmd: "docker compose down"
    chdir: "{{registry_dir}}"
  failed_when: false

- name: docker compose up -d
  shell:
    cmd: "docker compose up -d"
    chdir: "{{registry_dir}}"