---
- hosts: all
  become: yes
  roles:
    - role: system
      vars:
        - force_update_hostname: true
    - role: timezone
      vars:
        - timezone: Asia/Shanghai
    - role: ntp
      vars:
        - ntp_timezone: Asia/Shanghai