---
- name: "check: docker pull {{docker_repo_addr}}/{{image_file.repository}}:{{image_file.tag}}"
  delegate_to: localhost
  shell:
    cmd: "docker pull {{docker_repo_addr}}/{{image_file.repository}}:{{image_file.tag}}"
  register: docker_image_exist
  failed_when: false

- name: show docker_image_exist result
  delegate_to: localhost
  debug:
    msg: "{{docker_image_exist.stdout}}"

- include_tasks: import_repo_item.yml
  when:
    - "'not found' in docker_image_exist.stdout or '' == docker_image_exist.stdout"
