---
# 清空失效镜像： docker rmi `docker images | grep '<none>' | awk '{print $3}'`
- name: local docker tag from image tar files
  delegate_to: localhost
  shell:
    cmd: "docker tag {{image_file.repository}}:{{image_file.tag}} {{docker_repo_addr}}/{{image_file.repository}}:{{image_file.tag}}"

- name: local docker push from image tar files
  delegate_to: localhost
  shell:
    cmd: "docker push {{docker_repo_addr}}/{{image_file.repository}}:{{image_file.tag}}"