---
- name: Get mysql master addr from hosts for target
  set_fact:
    mysql_master_vip: "{{hostvars[item]['mysql_master_vip']}}"
  when: hostvars[item]['mysql_master_vip'] is defined and hostvars[item]['mysql_master_vip'] != 'auto'
  with_items: "{{groups['mysql']}}"

- name: Get mysql master addr from hosts for auto
  set_fact:
    mysql_master_vip: "{{hostvars[item]['ansible_ssh_host']}}"
  when: hostvars[item]['mysql_master_vip'] is defined and hostvars[item]['mysql_master_vip'] == 'auto'
  with_items: "{{groups['mysql']}}"

- name: "select count(*) from somersault_cloud_system.system_users;"
  shell: mysql -u"{{mysql_user}}" -p"{{mysql_passwd}}" -h"{{mysql_master_vip}}" -NBe "select count(*) from somersault_cloud_system.system_users;"
  register: initdata_count
  failed_when: false
  when:
    - hostvars[inventory_hostname]['mysql_master_vip'] is defined

- name: result of select count(*) from somersault_cloud_system.system_users
  debug:
    msg: "{{initdata_count.stdout}}"
  when:
    - hostvars[inventory_hostname]['mysql_master_vip'] is defined

- include_tasks: initdata.yml
  when:
    - hostvars[inventory_hostname]['mysql_master_vip'] is defined
    - initdata_count.stdout == '' or initdata_count.stdout == '0'
