---
- name: Include Linux variables
  include_vars: linux.yml

# 本地环境变量，一般涉密的一些配置，添加到.gitignore不上传到资源库
- name: Include local variables
  include_vars: local.yml
  ignore_errors: yes

- name: Check {{ frp }} version
  command: "{{frp_bin_dir}}/{{ frp }} --version"
  register: frp_version_installed
  changed_when: no
  failed_when: no

- name: Check frp latest version
  get_url:
    url: https://api.github.com/repos/fatedier/frp/releases/latest
  register: frp_version_latest
  when: frp_version == ""

- name: frp info
  include_tasks: ../frp_info.yml

# 下载太慢不稳定，改为本地文件上传模式
- name: Unarchive frp
  unarchive:
    src: "{{frp_release_name}}.{{frp_release_ext}}"
    dest: "{{ frp_tmp_dir }}"
  when: frp_outdated

- name: Include {{ frp }} installation
  include: install_frp.yml component={{ frp }}

- name: Include {{ frp }} configuration
  include: configure_frp.yml component={{ frp }}
