---
- name: set_fact docker_image_repo
  set_fact:
    docker_image_repo: "{{docker_repo_addr}}/"
  when: docker_repo_addr | default('') != ''

- name: create data dir
  file:
    path: "{{mysqld_exporter_dir}}/{{item}}"
    owner: '10001'
    state: directory
  loop:
    - "data"

- name: copy docker files
  template:
    src: "{{item}}"
    dest: "{{mysqld_exporter_dir}}/{{item}}"
  loop:
    - "docker-compose.yml"
    - "my-cnf.ini"

- name: docker compose down
  shell:
    cmd: "docker compose down"
    chdir: "{{mysqld_exporter_dir}}"
  failed_when: false

- name: docker compose up -d
  shell:
    cmd: "docker compose up -d"
    chdir: "{{mysqld_exporter_dir}}"