---
- name: Fetch download page
  uri:
    url: "{{ adoptopenjdk_api_page }}\
      assets/feature_releases/{{ java_major_version }}/ga\
      ?architecture={{ (java_arch == 'x64') | ternary('x64', 'x32') }}\
      &heap_size=normal\
      &image_type={{ java_package }}\
      &jvm_impl={{ adoptopenjdk_impl }}\
      &os=linux\
      &project=jdk\
      &vendor=adoptopenjdk"
    return_content: true
    follow_redirects: all
  register: download_page

- name: "Find release url"
  set_fact:
    release_url: >-
      {{ (download_page.content | from_json)[0].binaries | map(attribute='package.link') | list +
        (download_page.content | from_json)[0].binaries | map(attribute='package.checksum_link') | list }}

- name: Exit if AdoptOpenJDK version is not found
  fail:
    msg: 'AdoptOpenJDK version {{ java_major_version }} not found'
  when: release_url[0] is not defined

- name: 'Fetch artifact checksum file {{ release_url[1] }}'
  uri:
    url: '{{ release_url[1] }}'
    return_content: true
  register: artifact_checksum_file

- name: 'Get artifact checksum from file {{ release_url[1] }}'
  set_fact:
    artifact_checksum: >-
      {{ artifact_checksum_file['content']
        | regex_search('([^\s]+)') }}
    java_downloaded_file: >-
      {{ (release_url[0]|urlsplit).path|basename }}

- name: 'Download artifact from {{ release_url[0] }}'
  get_url:
    url: '{{ release_url[0] }}'
    dest: '{{ java_download_path }}/{{ java_downloaded_file }}'
    checksum: 'sha256:{{ artifact_checksum }}'
  register: file_downloaded
  retries: 20
  delay: 5
  until: file_downloaded is succeeded
