# 前台运行： docker compose up
# 后台运行： docker compose up -d
# 重建容器运行： docker compose up -d --build
# 显示构建信息运行： DOCKER_BUILDKIT=0  docker compose up -d --build
# 删除容器： docker compose down
version: "3.8"
services:

  xxl-job-admin:
    image: "xuxueli/xxl-job-admin:{{xxl_job_admin_version}}"
    container_name: xxl-job-admin
    restart: always
    volumes:
      # 日志目录映射到主机目录
      - ./logs:/data/applogs
    ports:
      - "{{xxl_job_port}}:{{xxl_job_port}}"
    environment:
      JAVA_OPTS: -Xms128M -Xmx256M
      # 设置启动参数
      PARAMS: '
      --server.port={{xxl_job_port}}
      --server.servlet.context-path=/xxl-job-admin
      --spring.datasource.url=jdbc:mysql://{{mysql_replication_master_addr}}/somersault_cloud_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
      --spring.datasource.username={{hostvars[groups['mysql'][0]]['mysql_user']}}
      --spring.datasource.password={{hostvars[groups['mysql'][0]]['mysql_passwd']}}
      --xxl.job.accessToken={{xxl_job_access_token}}'  #代码里面需要指定的token