---
# 本地环境变量，一般涉密的一些配置，添加到.gitignore不上传到资源库
- name: Include local variables
  include_vars: local.yml
  ignore_errors: yes

- name: create data dir
  file:
    path: "{{item}}"
    mode: "0755"
    state: directory
  loop:
    - "{{ddns_path}}"

- name: stop firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: stop selinux
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=disabled

- name: setenforce 0
  shell:
    cmd: "{{item}}"
  loop:
    - "setenforce 0"
  failed_when: false

- name: install tool software
  yum:
    name: [ 'dhclient' ]
    state: installed
  retries: 3

- name: replace /etc/sysctl.conf line
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: '^{{item[0]}} = .*$'
    line: '{{item[0]}} = {{item[1]}}'
    backrefs: no # 如果没有匹配，则添加一行line。如果匹配了，则把匹配内容替被换为line内容。
  loop:
    - [ 'net.ipv4.ip_forward','1' ]
    - [ 'net.ipv6.conf.all.accept_dad','0' ]
    - [ 'net.ipv6.conf.default.accept_dad','0' ]
    - [ 'net.ipv6.conf.{{ddns_network_interface}}.accept_dad','0' ]

- name: copy ddns shell fiile
  template:
    mode: "0755"
    src: ddns.sh
    dest: '{{ddns_path}}/ddns.sh'

- name: copy ddns jar file
  copy:
    src: "somersault-cloud-ddns.jar"
    dest: '{{ddns_path}}/somersault-cloud-ddns.jar'

- name: remove cache ip and execute ddns now
  shell:
    cmd: "{{item}}"
  loop:
    - "rm -f {{ddns_path}}/ip_last.txt"
    - "{{ddns_path}}/ddns.sh >> {{ddns_path}}/ddns.log"

# https://docs.ansible.com/ansible/2.9/modules/cron_module.html#cron-module
- name: crontab for update ddns
  cron:
    name: "每小时执行一次ipv6释放获取更新，以便同步获取运营商租约到期更新IP地址，然后执行DDNS动态刷新处理"
    minute: "{{cron_minute}}"
    job: "{{ddns_path}}/ddns.sh >> {{ddns_path}}/ddns.log"
