---
- name: set dest file path
  set_fact:
    dest_file: "{{role_path}}/files/html/{{download_file}}"

- name: Check primary package_file exists
  delegate_to: localhost
  become: false
  stat:
    path: "{{dest_file}}"
  register: download_file_result

- name: Creates directory
  file:
    path: "{{dest_file | dirname}}"
    state: directory
    mode: 0775
  when: download_file_result.stat.exists == False

- name: "primary download file {{download_file}} "
  delegate_to: localhost
  become: false
  #failed_when: false
  get_url:
    url: "{{primary_download_url_prefix}}{{download_file}}"
    dest: "{{dest_file}}"
    mode: "0755"
  when: download_file_result.stat.exists == False

- name: Check secondary package_file exists
  delegate_to: localhost
  become: false
  stat:
    path: "{{dest_file}}"
  register: download_file_result

- name: "secondary download file {{download_file}}"
  delegate_to: localhost
  become: false
  get_url:
    url: "{{secondary_download_url_prefix}}{{download_file}}"
    dest: "{{dest_file}}"
    mode: "0755"
  when: download_file_result.stat.exists == False