---
- name: stop node_exporter service
  shell: "systemctl stop node_exporter && systemctl disable node_exporter"
  failed_when: false

- name: disable keepalived service
  shell: "systemctl disable keepalived"
  failed_when: false

- name: kill keepalived service
  shell: "systemctl kill keepalived"
  failed_when: false

- name: stop & disable the firewall service.
  service:
    name: firewall
    state: stopped
    enabled: false
  failed_when: false

- name: remove /etc data files
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - "/etc/keepalived"
    - "/etc/init.d/firewall"
    - "/etc/firewall.bash"
  failed_when: false

- name: list dir
  shell:
    cmd: "ls /data"
  register: data_dir_list

- name: remove all data files
  shell:
    cmd: 'rm -fr {{item}}'
    chdir: "/data"
  when: item != 'cache'
  loop: "{{data_dir_list.stdout_lines}}"
  failed_when: false