---
- hosts: all
  gather_facts: true
  become: yes
  vars:
    - ansible_ssh_user: root
  vars_prompt:
    - name: confirm_clean
      prompt: "Dangerous!!! Confirm clean ALL docker package & data ? yes/no"
      default: "no"
      confirm: true
      private: false
  tasks:
  roles:
    - role: clean-docker