---
- name: set_fact
  set_fact:
    install_tmp_dir: /tmp/ansible/mysql_install

- name: create data dir
  file:
    path: "{{item}}"
    mode: "0755"
    state: directory
  loop:
    - "{{install_tmp_dir}}"

- name: copy rpm packages
  copy:
    src: "{{item}}"
    dest: "{{ install_tmp_dir }}/{{item | basename}}"
    owner: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    mode: 0777
  with_fileglob:
    - "{{role_path}}/files/*.rpm"
    - "{{role_path}}/files/*.tar.gz"

- name: Check if mysql file exists
  stat:
    path: "{{software_install_path}}/mysql/bin/mysqld"
  register: mysql_file_check

- name: "unarchive mysql file to {{ software_install_path }}"
  unarchive:
    src: "{{install_tmp_dir}}/{{ mysql_file }}"
    dest: "{{ software_install_path }}"
    owner: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    remote_src: true
  when: not mysql_file_check.stat.exists

- name: install rpm packages
  shell:
    cmd: "rpm -Uvh {{item | basename}} --nodeps --force"
    chdir: "{{ install_tmp_dir }}"
  with_fileglob:
    - "{{role_path}}/files/*.rpm"
  ignore_errors: true

- name: link mysql to bin path
  shell:
    cmd: "ln -s /usr/local/mysql/bin/mysql /usr/bin/mysql | cat"

- name: copy mysql.server to /etc/init.d
  copy:
    src: /usr/local/mysql/support-files/mysql.server
    dest: /etc/init.d/mysqld
    remote_src: yes

- name: append mysqld to auto startup
  shell:
    cmd: "{{item}}"
  loop:
    - "chmod a+wrx /etc/init.d/mysqld"
    - "chkconfig --level 345 mysqld on"
    - "chkconfig --list"