---
- name: disable docker service
  shell: "systemctl disable docker"
  retries: 3
  failed_when: false

- name: docker rm -f all docker containers
  shell: "docker rm -f $(docker ps -qa)"
  retries: 3
  failed_when: false

- name: docker rmi -f all docker images
  shell: "docker rmi -f $(docker images -qa)"
  retries: 3
  failed_when: false

- name: docker image prune -f -a
  shell: "docker image prune -f -a"
  retries: 3
  failed_when: false

#- name: reboot host for docker system resource release
#  reboot:

- name: remove all docker dir
  file:
    path: '{{ item }}'
    state: absent
  loop:
    - "/etc/docker"
    - "/run/docker"
    - "/var/run/docker"
    - "/var/lib/docker"
#    - "/var/lib/dockershim"
  ignore_errors: true

# yum list installed|grep docker OR rpm -qa|grep docker
- name: remove docker package
  shell: "yum -y remove {{item}}"
  loop:
    - "containerd.io.{{ansible_architecture}}"
    - "docker-buildx-plugin.{{ansible_architecture}} "
    - "docker-ce.{{ansible_architecture}}"
    - "docker-ce-cli.{{ansible_architecture}}"
    - "docker-ce-rootless-extras.{{ansible_architecture}}"
    - "docker-compose-plugin.{{ansible_architecture}}"
  ignore_errors: true





