---
- name: setting vars
  set_fact:
    service_name: "{{service_config.name}}"
    service_port_config: "{{service_config}}"
    port_start: "{{service_config.port }}"

- name: print service config
  debug:
    msg: "{{service_config}}"

- name: Include port.yml task
  include_tasks: port.yml
  vars:
    service_port_index: "{{item | int}}"
    service_port_number: "{{port_start | int + item | int}}"
  with_sequence: start=0 end={{service_config.replicas | int - 1 }}
